---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Confirm privilege escalation is working
      command: whoami
      register: whoami_check
      become: true

    - debug:
        msg: "Running as {{ whoami_check.stdout }}"

    # Rest of your APT tasks...
